### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by hilljh82** [onehilltech/blueprint#53]
v4 will be a major update to the code base. It is expected to break existing code bases, and we will not provide support for backwards compatibility. The list below is a list of features we plan on putting in v4. As we work on the update, expect this list to change. 

### Proposed Features
- [x] Upgrade code base to use ES6 via [core-object](https://github.com/ember-cli/core-object)
  - [x] Create Listener object and LegacyListener object for porting existing listeners
  - [x] Create Controller object and LegacyController object for porting existing controllers
  - [x] Create Router object and LegacyRouter object for porting existing routers
  - [x] Create Policy object and LegacyPolicy object for porting existing policies
  - [x] Move listener objects to their own module
- [x] Create Service abstraction for objects that live the entire life of the application outside of existing object types.
- [x] Improve inheritance support in library classes
- [x] Add support for synchronous messaging
- [x] Improve testing infrastructure for Blueprint modules
- [x] Switch from callback architecture to Promise architecture
- [x] Prepend `blueprint.` to built-in message types
- [x] Replace underscore with [lodash](https://lodash.com/)

### General Tasks
- [x] Update test cases

**Comment by hilljh82** [comment]
We are making good progress on v4. Our next steps involve updating the examples to make sure v4 meets our design expectations.

**Comment by hilljh82** [comment]
In addition to the previous comment, we now have the ability to bind services and models to object properties. This means that we no longer have to manually import a model. Instead, we can reference it via its string property. For example, here is how you can bind a service and model to a controller definition:

```
module.exports = Controller.extend ({
  shoppingCart: service ('shopping-cart'),
  person: model ()
});
```

**Comment by hilljh82** [comment]
v4 is complete, and is now released.
